version: 2
jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: rustup version
          command: rustup --version
      - run:
          name: rustup component add
          command: rustup component add clippy
      - restore_cache:
          keys:
            - v1-cargo-lock-{{ checksum "Cargo.lock" }}
      - run:
          name: build
          command: cargo build;
      - run:
          name: lint
          command: cargo clippy -- -D warnings
      - save_cache:
          key: v1-cargo-lock-{{ checksum "Cargo.lock" }}
          paths:
            - "/usr/local/cargo/registry"
            - "target"
